import localFont from "next/font/local";
import "./globals.css";
import { roboto, inter, montserrat } from "../utils/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto} ${inter} ${montserrat}`}
      >
        {children}
      </body>
    </html>
  );
}
